from .schemas import (
    PredictionResponse,
    HistoryResponse,
    GradesResponse,
    LoginRequest,
    TokenResponse,
    ClinicCreate,
    ClinicUpdate,
    ClinicResponse,
    ClinicAdminCreate,
    ClinicAdminResponse,
    DoctorCreate,
    DoctorResponse,
    PatientRegister,
    PatientCreate,
    PatientUpdate,
    PatientResponse,
)
