from .diagnostic import router as diagnostic_router
from .chat import router as chat_router
from .auth import router as auth_router
from .superadmin import router as superadmin_router
from .clinic_admin import router as clinic_admin_router
from .clinics import router as clinics_router
from .doctors import router as doctors_router
from .patients import router as patients_router
from .anketa import router as anketa_router
from .doctor_patient_chat import router as dp_chat_router
from .nurses import router as nurses_router
